Registration
Balto-ai/balto-app pull request #36
Opened 2022-07-29 23:33 UTC by chcx97

- converted css to bootstrap

2022-07-31 19:02 UTC, annesatran approved these changes
I think we should probably remove the console logs, other than that it looks good

2022-08-01 15:23 UTC, LifeBringer approved these changes
See comments

2022-08-01 15:23 UTC, LifeBringer commented on balto-ui/src/components/RegistrationForm/RegistrationForm.jsx
> +  console.log('errors',errors)
Replace with console.error

2022-08-01 15:23 UTC, LifeBringer commented on balto-ui/src/components/RegistrationForm/RegistrationForm.jsx
> +  console.log('form',form)
What Annesa said

2022-08-01 15:23 UTC, LifeBringer commented on balto-ui/src/components/RegistrationForm/RegistrationForm.jsx
>        console.log(form)
Console.error where applicable

2022-08-01 15:23 UTC, LifeBringer requested changes
See review

2022-08-01 17:09 UTC, LifeBringer commented
You can hit 'resolve' once the issues are addressed.

2022-08-01 17:11 UTC, LifeBringer approved these changes

2022-08-01 17:12 UTC, merged